/*
 * 
 * File: Configurations.java
 * 
 * Copyright (C) 2015, Nuance Communications Inc. All Rights Reserved.
 * 
 */

package com.theboss.jackli.friendtain.configurations;
/**
 * Class that defines the application variables
 * This class is generated by a script before donwloading and the variables are populated from the user account provided by Nuance.
 *
 */
public class Configurations
{
	/**
	 * NMAID ID
	 */
	public static String NMAID_ID = "JackLiCo_JackLiApp_20160124_090029";
	/**
	 * NMAID Key as string
	 */
	public static final String NMAID_KEY_STRING = "0x90 0xb1 0x41 0xe5 0xd6 0x0a 0x13 0x27 0xd6 0x22 0xd9 0x43 0xb0 0xb8 0x00 0x50 0x18 0x12 0xa6 0x4d 0x16 0xec 0xdc 0x6e 0xbd 0xb3 0x50 0x39 0xed 0x11 0x3d 0x5f 0x08 0x9e 0x57 0x4e 0x02 0xa3 0x0d 0x88 0x37 0x8f 0x75 0x8c 0x90 0xab 0x42 0x51 0x2d 0x1d 0x77 0x91 0x85 0xc0 0xe6 0xae 0x86 0x75 0xe9 0x31 0xbd 0x8e 0x07 0xec";
	/**
	 * Application Name
	 */
	public static String APPLICATION_NAME = "JackLiApp";
	/**
	 * Application version
	 */
	public static String APPLICATION_VERSION = "0.0";
	/**
	 * Company Name
	 */
	public static String COMPANY_NAME = "JackLiCo";

	/**
	 * Server IP address or host name to connect to
	 */
	public static String GATEWAY_HOST = "nim-rd.nuance.mobi";

	/**
	 * Port number
	 */
	public static int GATEWAY_PORT = 443;

	/**
	 * Gateway SSL 
	 */
	public static boolean GATEWAY_USE_SSL = true;

	/**
	 * Gateway SSL certificate
	 */
	public static boolean GATEWAY_VERIFY_SSL_CERTIFICATE = false;

	/**
	 * Server Application name
	 */
	public static String SERVER_APPLICATION_NAME = "NinaCloud";

	/**
	 * Default Nina voice for TTS prompts. The spelling should be exactly the same of a voice enabled for your application by Nuance
	 */
	public static String TTS_VOICE_NAME = "Carol";
	/**
	 * Default Nina locale for TTS prompts. The spelling should be exactly the same of a locale enabled for your application by Nuance
	 */
	public static String TTS_VOICE_LOCALE = "en";
}
